# Generated by Django 4.2.13 on 2025-04-25 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_last_viewed"),
        ("jobs", "0007_job_last_viewed"),
    ]

    operations = []
