# Generated by Django 4.2.13 on 2025-04-25 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0001_wikipage_published_alter_wikipage_content_and_more"),
        ("wiki", "0003_wikipage_published_alter_wikipage_content_and_more"),
    ]

    operations = []
