# Generated by Django 4.2.13 on 2025-04-25 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "__first__"),
        ("wiki", "0004_merge_20250425_0553"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikipage",
            name="brief_description",
            field=models.CharField(
                blank=True,
                help_text="A brief description that appears on index pages (255 chars max).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="mush_group",
            field=models.OneToOneField(
                blank=True,
                help_text="Associated MUSH Group (only for group pages)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wiki_page",
                to="groups.group",
            ),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="page_type",
            field=models.CharField(
                choices=[("regular", "Regular"), ("group", "Group"), ("plot", "Plot")],
                default="regular",
                help_text="Type of wiki page (regular, group, or plot)",
                max_length=10,
            ),
        ),
    ]
