# Generated by Django 4.2.13 on 2025-04-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0005_wikipage_brief_description_wikipage_mush_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikipage",
            name="lock_settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Lock settings for this page. Format: {'has_splat': 'Vampire', 'has_clan': 'Brujah'}. Supported lock types: has_splat, has_type, has_clan, has_tribe, has_auspice, has_tradition, has_affiliation, has_convention, has_nephandi_faction, has_court, has_kith.",
            ),
        ),
        migrations.AlterField(
            model_name="wikipage",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="wikipage",
            name="is_index",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="wikipage",
            name="page_type",
            field=models.IntegerField(
                choices=[(0, "Regular"), (1, "Group"), (2, "Plot")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="wikipage",
            name="related_to",
            field=models.ManyToManyField(blank=True, to="wiki.wikipage"),
        ),
    ]
