# Generated by Django 4.2.13 on 2025-05-12 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "0014_defaultobject_crisis_defaultcharacter_defaultexit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("downtime_cost", models.IntegerField(default=0)),
                ("requires_target", models.BooleanField(default=False)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("retainer", "Retainer"),
                            ("haven", "Haven"),
                            ("territory", "Territory"),
                            ("contact", "Contact"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("value", models.IntegerField(default=0)),
                ("owner_id", models.IntegerField()),
                ("status", models.CharField(default="Active", max_length=50)),
                ("traits", models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MokoleArchidTrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("can_stack", models.BooleanField(default=False)),
                ("stat_modifiers", models.JSONField(default=dict)),
                ("special_rules", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Roster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "sphere",
                    models.CharField(
                        choices=[
                            ("mage", "Mage"),
                            ("vampire", "Vampire"),
                            ("werewolf", "Werewolf"),
                            ("changeling", "Changeling"),
                            ("hunter", "Hunter"),
                            ("wraith", "Wraith"),
                            ("demon", "Demon"),
                            ("mortal", "Mortal"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admins",
                    models.ManyToManyField(
                        blank=True,
                        related_name="administered_rosters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hangouts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="roster_hangouts",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "managers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="managed_rosters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Stat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(default="")),
                ("game_line", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("attributes", "Attributes"),
                            ("abilities", "Abilities"),
                            ("secondary_abilities", "Secondary Abilities"),
                            ("advantages", "Advantages"),
                            ("backgrounds", "Backgrounds"),
                            ("powers", "Powers"),
                            ("merits", "Merits"),
                            ("flaws", "Flaws"),
                            ("traits", "Traits"),
                            ("identity", "Identity"),
                            ("archetype", "Archetype"),
                            ("virtues", "Virtues"),
                            ("legacy", "Legacy"),
                            ("pools", "Pools"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "stat_type",
                    models.CharField(
                        choices=[
                            ("attribute", "Attribute"),
                            ("ability", "Ability"),
                            ("secondary_ability", "Secondary Ability"),
                            ("advantage", "Advantage"),
                            ("background", "Background"),
                            ("lineage", "Lineage"),
                            ("discipline", "Discipline"),
                            ("combodiscipline", "Combo Discipline"),
                            ("thaumaturgy", "Thaumaturgy"),
                            ("gift", "Gift"),
                            ("rite", "Rite"),
                            ("sphere", "Sphere"),
                            ("rote", "Rote"),
                            ("art", "Art"),
                            ("splat", "Splat"),
                            ("edge", "Edge"),
                            ("special_advantage", "Special Advantage"),
                            ("realm", "Realm"),
                            ("blessing", "Blessing"),
                            ("path", "Path"),
                            ("sorcery", "Sorcery"),
                            ("faith", "Faith"),
                            ("numina", "Numina"),
                            ("hedge_ritual", "Hedge Ritual"),
                            ("enlightenment", "Enlightenment"),
                            ("power", "Power"),
                            ("virtue", "Virtue"),
                            ("vice", "Vice"),
                            ("merit", "Merit"),
                            ("flaw", "Flaw"),
                            ("possessed_type", "Possessed Type"),
                            ("trait", "Trait"),
                            ("skill", "Skill"),
                            ("knowledge", "Knowledge"),
                            ("talent", "Talent"),
                            ("secondary_knowledge", "Secondary Knowledge"),
                            ("secondary_talent", "Secondary Talent"),
                            ("secondary_skill", "Secondary Skill"),
                            ("specialty", "Specialty"),
                            ("physical", "Physical"),
                            ("social", "Social"),
                            ("mental", "Mental"),
                            ("personal", "Personal"),
                            ("supernatural", "Supernatural"),
                            ("moral", "Moral"),
                            ("temporary", "Temporary"),
                            ("dual", "Dual"),
                            ("renown", "Renown"),
                            ("arete", "Arete"),
                            ("banality", "Banality"),
                            ("glamour", "Glamour"),
                            ("essence", "Essence"),
                            ("quintessence", "Quintessence"),
                            ("blood", "Blood"),
                            ("rage", "Rage"),
                            ("gnosis", "Gnosis"),
                            ("willpower", "Willpower"),
                            ("resonance", "Resonance"),
                            ("synergy", "Synergy"),
                            ("paradox", "Paradox"),
                            ("kith", "Kith"),
                            ("phyla", "Phyla"),
                            ("seeming", "Seeming"),
                            ("house", "House"),
                            ("seelie-legacy", "Seelie Legacy"),
                            ("unseelie-legacy", "Unseelie Legacy"),
                            ("court", "Court"),
                            ("tribe", "Tribe"),
                            ("camp", "Camp"),
                            ("breed", "Breed"),
                            ("clan", "Clan"),
                            ("companion_type", "Companion Type"),
                            ("mortalplus_type", "Mortal+ Type"),
                            ("varna", "Varna"),
                        ],
                        max_length=100,
                    ),
                ),
                ("values", models.JSONField(blank=True, default=list, null=True)),
                (
                    "lock_string",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "splat",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                ("xp_cost", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "prerequisites",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "shifter_type",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of shifter types that can learn this gift",
                        null=True,
                    ),
                ),
                (
                    "gift_alias",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of alternative names for this gift",
                        null=True,
                    ),
                ),
                ("hidden", models.BooleanField(default=False)),
                ("locked", models.BooleanField(default=False)),
                (
                    "instanced",
                    models.BooleanField(
                        default=None,
                        help_text="If True, requires an instance. If False, disallows instances. If null, instances are optional.",
                        null=True,
                    ),
                ),
                (
                    "default",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "auspice",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("ragabash", "Ragabash"),
                            ("theurge", "Theurge"),
                            ("philodox", "Philodox"),
                            ("galliard", "Galliard"),
                            ("ahroun", "Ahroun"),
                            ("brightwater", "Brightwater"),
                            ("dimwater", "Dimwater"),
                            ("darkwater", "Darkwater"),
                            ("kamakshi", "Kamakshi"),
                            ("kartikeya", "Kartikeya"),
                            ("kamsa", "Kamsa"),
                            ("kali", "Kali"),
                            ("rising_sun", "Rising Sun"),
                            ("noonday_sun", "Noonday Sun"),
                            ("shrouded_sun", "Shrouded Sun"),
                            ("midnight_sun", "Midnight Sun"),
                            ("decorated_sun", "Decorated Sun"),
                            ("solar_eclipse", "Solar Eclipse"),
                        ],
                        default="none",
                        max_length=100,
                    ),
                ),
                (
                    "breed",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("homid", "Homid"),
                            ("metis", "Metis"),
                            ("lupus", "Lupus"),
                            ("feline", "Feline"),
                            ("squamus", "Squamus"),
                            ("ursine", "Ursine"),
                            ("latrani", "Latrani"),
                            ("rodens", "Rodens"),
                            ("corvid", "Corvid"),
                            ("balaram", "Balaram"),
                            ("vasuki", "Vasuki"),
                            ("ahi", "Ahi"),
                            ("arachnid", "Arachnid"),
                            ("kojin", "Kojin"),
                            ("shinju", "Shinju"),
                            ("roko", "Roko"),
                            ("suchid", "Suchid"),
                            ("hyaenid", "Hyaenid"),
                        ],
                        default="none",
                        max_length=100,
                    ),
                ),
                (
                    "tribe",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tribes that can learn this gift",
                        null=True,
                    ),
                ),
                (
                    "camp",
                    models.CharField(
                        blank=True,
                        help_text="Specific camp that can learn this gift",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Source book reference",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "system",
                    models.TextField(
                        blank=True, help_text="Game mechanics description", null=True
                    ),
                ),
                (
                    "mortalplus_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ghoul", "Ghoul"),
                            ("kinfolk", "Kinfolk"),
                            ("kinain", "Kinain"),
                            ("sorcerer", "Sorcerer"),
                            ("psychic", "Psychic"),
                            ("faithful", "Faithful"),
                            ("none", "None"),
                        ],
                        default="none",
                        help_text="Type of Mortal+ character",
                        max_length=100,
                    ),
                ),
                (
                    "guildmarks",
                    models.CharField(
                        blank=True,
                        default="none",
                        help_text="Type of guildmarks",
                        max_length=200,
                        null=True,
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "category", "stat_type", "splat")},
            },
        ),
        migrations.CreateModel(
            name="ShapeshifterForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("shifter_type", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("stat_modifiers", models.JSONField(default=dict)),
                ("rage_cost", models.IntegerField(default=0)),
                ("difficulty", models.IntegerField(default=6)),
                (
                    "lock_string",
                    models.CharField(
                        default="examine:all();control:perm(Admin)", max_length=255
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "shifter_type")},
            },
        ),
        migrations.CreateModel(
            name="CharacterSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_sheet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "character",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_sheet",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "db_object",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="db_character_sheet",
                        to="objects.objectdb",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="character_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_id", models.IntegerField()),
                ("downtime_spent", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("result", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "target_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="targeted_by_actions",
                        to="wod20th.asset",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wod20th.actiontemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RosterMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("approved", models.BooleanField(default=False)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_roster_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_memberships",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "roster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="wod20th.roster",
                    ),
                ),
            ],
            options={
                "ordering": ["character__db_key"],
                "unique_together": {("roster", "character")},
            },
        ),
        migrations.CreateModel(
            name="CharacterArchidTrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField(default=1)),
                ("approved", models.BooleanField(default=False)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_archid_traits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archid_traits",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wod20th.mokolearchidtrait",
                    ),
                ),
            ],
            options={
                "ordering": ["trait__name"],
                "unique_together": {("character", "trait")},
            },
        ),
    ]
