# Generated by Django 4.2.13 on 2025-05-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plots", "0002_alter_plot_risk_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="event_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
