# Generated by Django 4.2.13 on 2025-05-12 04:32

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "0014_defaultobject_crisis_defaultcharacter_defaultexit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HangoutDB",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objects.objectdb",),
        ),
    ]
